НОВЫй МОД UPL Подземные линии электропередач
FactorioParanoidal/ParanoidalModpack pull request #100
Opened 2024-08-23 00:48 UTC by ExpertLove

2024-08-23 17:52 UTC, ProTriforcer approved these changes

2024-08-23 18:38 UTC, ProTriforcer commented on mods/underground-energy-distribution/prototypes/large_db.lua
> +large_db.supply_area_distance	        = 9
Надо увеличить на 0.5, а то покрытие с сеткой не совпадает
![image](https://github.com/user-attachments/assets/1ac9b14b-1f17-4721-b1f1-f176ee30a8fa)

2024-08-23 19:25 UTC, ProTriforcer commented
Без коллизии они абузными будут. Хоть на синие банки их ставь, хоть на фиолетовые, после них другие столбы не актуальны. Зачем открывать и крафтить топовую подстанцию, когда есть стаки подземных столбов?

2024-08-27 13:43 UTC, SKProCH requested changes
Изменения, описанные в комментах звучит разумно

2024-08-27 14:16 UTC, SKProCH approved these changes

2024-08-27 14:26 UTC, merged