Обновление фабрик
FactorioParanoidal/ParanoidalModpack pull request #161
Opened 2024-09-23 00:29 UTC by ProTriforcer

#160 но не в архиве

2024-09-23 00:30 UTC, drd-avel approved these changes
Продолжаем пробовать...

2024-09-24 22:04 UTC, SKProCH requested changes
Т.к. лэаут старых фабрик поменялся, что будет с уже существующими? Они останутся, как есть? При сносе фабрики в инвентарь и повторном его размещении?

2024-09-24 22:04 UTC, SKProCH commented on mods/factorissimo-2-notnotmelon/control.lua
> +	-- surface.set_chunk_generated_status({cx-1, cy-2}, defines.chunk_generated_status.entities)
Я бы их в принципе выпилил

2024-09-24 22:04 UTC, SKProCH commented on mods/factorissimo-2-notnotmelon/graphics/factory/factory-1-alt.png
Графика действительно поменялась?

2024-09-24 22:04 UTC, SKProCH commented on mods/factorissimo-2-notnotmelon/script/connections/connections.lua
> +local beeps = {'Не трогай!', 'Убери руки', 'Не работает', 'Функция в отпуске'}
Унести в локализацию(?)

2024-09-24 22:04 UTC, SKProCH commented on mods/factorissimo-2-notnotmelon/script/pollution.lua
> +	-- chunk = {inside_x + 16,inside_y - 16}
Выпилить комменты

2026-04-13 23:00 UTC, closed without merging