Для сборщика электроники нужны фиол. манипуляторы
FactorioParanoidal/ParanoidalModpack pull request #62
Opened 2024-05-04 09:54 UTC by AKMFrtx

2024-05-04 11:39 UTC, SKProCH requested changes
Можешь в info.json поднять версию?

2024-05-06 17:10 UTC, AKMFrtx commented
> Можешь в info.json поднять версию?
в этом реквесте могу или пересоздавать надо?

2024-05-06 18:11 UTC, SKProCH commented
Да, в этом
Просто ещё коммит запушить в эту же ветку.

2024-05-09 18:39 UTC, AKMFrtx commented
> Да, в этом Просто ещё коммит запушить в эту же ветку.

а как?

2024-05-09 21:37 UTC, merged